//! Generated shader pipeline constants
//!
//! This module contains pre-compiled Anime4K shader pipelines generated by the build script.
//! All pipelines are optimized for GPU execution with pre-allocated resources and
//! embedded shader code for maximum performance.

include!(concat!(env!("OUT_DIR"), "/pipelines.rs"));
